#!/usr/bin/env ruby

$LOAD_PATH << File.join(__dir__, "../lib")
require "parser/ruby25"
Parser::Builders::Default.emit_lambda = true
Parser::Builders::Default.emit_procarg0 = true

require "ast_utils"
require "ast_utils/cli"

ASTUtils::CLI.start(ARGV)
